create table if not exists public.credit_orders (
  id bigint generated by default as identity primary key,
  order_id text unique not null,
  user_id uuid not null references auth.users(id) on delete cascade,
  credit_amount integer not null,
  amount_try numeric(12,2) not null,
  provider text not null default 'iyzico',
  iyzico_token text,
  status text not null default 'pending',
  provider_response jsonb,
  created_at timestamptz not null default now(),
  paid_at timestamptz
);

create index if not exists credit_orders_user_id_idx on public.credit_orders(user_id);
create index if not exists credit_orders_status_idx on public.credit_orders(status);

-- Credits are added exactly once, inside one database transaction.
create or replace function public.complete_credit_order(p_order_id text, p_provider_response jsonb)
returns public.credit_orders
language plpgsql
security definer
set search_path = public
as $$
declare
  o public.credit_orders;
begin
  select * into o from public.credit_orders where order_id=p_order_id for update;
  if not found then raise exception 'ORDER_NOT_FOUND'; end if;
  if o.status='paid' then return o; end if;
  update public.profiles set credits=coalesce(credits,0)+o.credit_amount where id=o.user_id;
  update public.credit_orders set status='paid', paid_at=now(), provider_response=p_provider_response where order_id=p_order_id returning * into o;
  return o;
end;
$$;
